set_property PACKAGE_PIN A15 [get_ports sda]
set_property PACKAGE_PIN N16 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN Y18 [get_ports clk_50m]
set_property PACKAGE_PIN E3 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports io_intr]
set_property PACKAGE_PIN C15 [get_ports io_intr]

set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dis_datx2[0]}]
set_property PACKAGE_PIN V2 [get_ports {o_dis_datx1[3]}]
set_property PACKAGE_PIN U3 [get_ports {o_dis_datx1[2]}]
set_property PACKAGE_PIN T3 [get_ports {o_dis_datx1[1]}]
set_property PACKAGE_PIN T1 [get_ports {o_dis_datx1[0]}]
set_property PACKAGE_PIN AA1 [get_ports {o_dis_datx2[3]}]
set_property PACKAGE_PIN Y3 [get_ports {o_dis_datx2[2]}]
set_property PACKAGE_PIN W2 [get_ports {o_dis_datx2[1]}]
set_property PACKAGE_PIN F17 [get_ports {o_dis_datx2[0]}]

set_property PACKAGE_PIN B15 [get_ports scl]
set_property PACKAGE_PIN W1 [get_ports {o_dis_datx2[0]}]

set_property PACKAGE_PIN A15 [get_ports sda]
set_property PACKAGE_PIN N16 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN Y18 [get_ports clk_50m]
set_property PACKAGE_PIN E3 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports io_intr]
set_property PACKAGE_PIN C15 [get_ports io_intr]