# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a75tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado2/max30102x3/prj/prj.cache/wt [current_project]
set_property parent.project_path D:/vivado2/max30102x3/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado2/max30102x3/prj/prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/vivado2/max30102x3/prj/prj.srcs/sources_1/new/ana_show.v
  D:/vivado2/max30102x3/prj/prj.srcs/sources_1/new/iic_phy.v
  D:/vivado2/max30102x3/prj/prj.srcs/sources_1/new/max30102_driver.v
  D:/vivado2/max30102x3/prj/prj.srcs/sources_1/new/top.v
}
read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_div/floating_div.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_div/floating_div_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_add/floating_add.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_add/floating_add_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_mult/floating_mult.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/floating_mult/floating_mult_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/sum/sum.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/sum/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/sum/sum_ooc.xdc]

read_ip -quiet D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf.xci
set_property used_in_implementation false [get_files -all d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado2/max30102x3/prj/prj.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files D:/vivado2/max30102x3/prj/prj.srcs/constrs_1/new/led.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a75tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
