# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf.xci
# IP: The module: 'float_tf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_tf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf.xci
# IP: The module: 'float_tf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado2/max30102x3/prj/prj.srcs/sources_1/ip/float_tf/float_tf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_tf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
